apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: collection
  description: A collection of Software Templates
spec:
  type: url
  targets:
    - templates/github/go-backend/template.yaml