apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: go-backend-template
  title: Create a Go Backend application
  description: Create a starter Go backend application
  tags:
    - recommended
    - go
spec:
  owner: akiyoshi-yonekura
  system: go-backend-system
  type: service

  parameters:
    - title: Provide information about the new component
      required:
        - orgName
        - repoName
        - owner
        - system
        - port
      properties:
        orgName:
          title: Organization Name
          type: string
        repoName:
          title: Repository Name
          type: string
        description:
          title: Description
          type: string
          description: Help others understand what this component is for
        owner:
          title: Owner
          type: string
          ui:field: EntityPicker
          ui:options:
            catalogFilter:
              kind:
                - Group
                - User
        system:
          title: System
          type: string
          ui:field: EntityPicker
          ui:options:
            catalogFilter:
              kind:
                - System
        port:
          title: Port
          type: number
          default: 8080
          description: Override the port exposed for the application
    - title: Provide information about the platform
      required:
        - platform
      properties:
        platform:
          title: Select a platform
          type: string
          description: This action will create a platform for your application
          default: ../../../skeletons/k8s-manifests/kustomize
          enum:
            - ../../../skeletons/k8s-manifests/kustomize
            - ../../../skeletons/k8s-manifests/manifests
          enumNames:
            - Kubernetes with kustomize
            - Kubernetes with manifests
  steps:
    - id: sourceCodeTemplate
      name: Generating the Source Code Component
      action: fetch:template
      input:
        url: ../../../skeletons/go-backend/
        targetPath: ./app
        values:
          orgName: ${{ parameters.orgName }}
          repoName: ${{ parameters.repoName }}
          owner: ${{ parameters.owner }}
          system: ${{ parameters.system }}
          applicationType: api
          description: ${{ parameters.description }}
          namespace: ${{ parameters.namespace }}
          imageUrl: ${{ parameters.imageUrl }}
          imageBuilder: s2i-go
          imageRepository: ${{ parameters.imageRepository }}
          port: ${{ parameters.port }}
          ci: ${{ parameters.ci }}
          sourceControl: github.com
    - id: platformTemplate
      name: Generating the Platform Component
      action: fetch:template
      input:
        url: ${{ parameters.platform }}
        targetPath: ./platform
        values:
          orgName: ${{ parameters.orgName }}
          repoName: ${{ parameters.repoName }}-platform
          owner: ${{ parameters.owner }}
          system: ${{ parameters.system }}
          applicationType: platfrom
          description: ${{ parameters.description }}
          namespace: ${{ parameters.namespace }}-platfrom
          imageUrl: ${{ parameters.imageUrl }}
          imageRepository: ${{ parameters.imageRepository }}
          port: ${{ parameters.port }}
          platform: ${{ parameters.platform }}
          sourceControl: github.com

    - id: catalogTemplate
      name: Generating the Catalog Info Component
      action: fetch:template
      input:
        url: ../../../skeletons/catalog-info/
        targetPath: ./app
        values:
          orgName: ${{ parameters.orgName }}
          repoName: ${{ parameters.repoName }}
          owner: ${{ parameters.owner }}
          system: ${{ parameters.system }}
          applicationType: api
          description: ${{ parameters.description }}
          namespace: ${{ parameters.namespace }}
          imageUrl: ${{ parameters.imageUrl }}
          imageBuilder: s2i-go
          imageRepository: ${{ parameters.imageRepository }}
          port: ${{ parameters.port }}
          ci: ${{ parameters.ci }}
          sourceControl: github.com

    - id: publish-app
      name: Publishing to the Source Code Repository
      action: publish:github
      input:
        allowedHosts: ['github.com']
        description: ${{ parameters.description }}
        repoUrl: github.com?owner=${{ parameters.orgName }}&repo=${{ parameters.repoName }}
        defaultBranch: main
        sourcePath: ./app

    - id: publish-platform
      name: Publishing to the Platform Code Repository
      action: publish:github
      input:
        allowedHosts: ['github.com']
        description: ${{ parameters.description }}
        repoUrl: github.com?owner=${{ parameters.orgName }}&repo=${{ parameters.repoName }}-platform
        defaultBranch: main
        sourcePath: ./platform

    - id: register
      name: Registering the Catalog Info Component
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: /catalog-info.yaml

  output:
    links:
      - title: Open the Source Code Repository
        url: ${{ steps.publish-app.output.remoteUrl }}
      - title: Open the Platform Code Repository
        url: ${{ steps.publish-platform.output.remoteUrl }}
      - title: Open the Catalog Info Component
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
